language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: fgmacedo
  password:
    secure: DK1Ylg3vHhGlehg94oLgyirGVYRrLwQhGSD+wGqTXixOKC47r2rJPzL7DSFx/BGgpsKZHeNLyvtMVLZjD6SNUM8hak1kriRxGO+ABHUVSQL1GcxSzsZTP1HHwmlhRXkHjIZZqDvAGaGtzvWYIoKAVneeO9l3xaVzEkitMjQd6YQdyiRgHoEYby2bf3AyObnUQo5A+aCWBNnZhXP6K4aVv09PZ2zGWbBuD6Xy5CuoGxiyeXFPrRVe4LlNz38Ay1KpWKHPS9Aq+OMItgNwSZR/Ib7Vgnu/RrqSxb6UvToECzff5eNngcnRf3/va97IDxjpRBwXkH8LmBLWFvUy4mjB297sno2D4xMemOg0G0FjerkzdyEWF5idAxsPZ3mhQiwateegXZ3GPAp4Gnn6ExfuYoay/bZyyasaRAdf/x4pOyFmx3f1GzQeGIwLJAlFrcDhN7dbPqftsnYPxISrfWQ0BmeqZ4r79wdaGGvquV75pwJi96II2MGwl0uxOHhLHzaC2KNY68C6DK3WV8kwU/9pa7tIJsId6mrrHhos+UOcBqzuswOMGnFOT9XEN5lPck5P7OK8hoISjsf5dX/lg6OVs2+AHfK9bugOa5jQnHeQbDU6JHbfO3HEazs041Nvmtkim5oEm2eRxVZH3jj+3Shy7XAmHCFbPkana4rbetp3E34=
  on:
    tags: true
    repo: fgmacedo/soonerdb
    python: 3.9
