language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
before_install:
- pip install codecov
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: nqgg8CJtPVtvpqg+1zsVtquBqa0nysYfJ2+MqXHLcXzBdyCabavbA4WlBom45wjJcEI3Yubkn1NytwJz+ZoSUhtiEr7oYbaWN/qOVuRTgvPhbxvgq30pkvQ/eu9y3AI482hdIOloFMycnmjzIPWc0ka/qKPsAdrospacSolzCs2qj1yR/yEqbTF2/PCQeVXL8HB9lS3UeEO7tB/MGXGefBEIEwXtUm3LEkqZR4aTbOahuF0mmOsvAI4XVNcPof6FcJgF/rIIpsehjNyG6zviZOx8F905NyxHVfh1nMqIMFMqHwOJyITePE8ATZTfTv6G0Kwm9hq142YCFIO5B1r1Jk/qJbz5zFghceq3Eg9ipbfFjncC9qTTL16EsfWvukzxlYuuXWH2Io9iekYvud6qo4ZwzleQa9MI09OBlP6pib9xlKkLYpg+bBjkC+knGsybWVvI2+25g2oDlVj+UM/is+KPM0k5iJYSUt+yBY20KLZR6v1Tixxs+oeYy5W8M/G58xSIXpSSyVkt6UMZ6GK9XWOjo39HQnmJeCwtv7OsnPt8XDdlYCcb8dp1gLYUIU91CWezXo3dqa8dYAnodNhf8DRfwiibdKJIUIenoe4ehX0Jxkc/pRbD2yPFz5Z3nzYYezrrVqAacogHyGNWsOWeVYd0NyZTKiipXaKr4C8ekjk=
  on:
    tags: true
    repo: fgmacedo/soonerdb
    python: 3.9
after_success:
- codecov
