language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
before_install:
  - pip install codecov
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: QkLODVwwMO9k5sj40AjgKFlq3bKb0CE8X/Y5elR11kaX83DjMynkNb7kMr0FHpgAAQ5HCjdv4vX0qnV3UjsjiQtZiNOnPL42IPLIr14bwd4azPccuH4SKB65ymd7dtPivvUU8NwX0DnM+Pk1cv7K2rnN3Fkz1KZuYK0zzQbgXWawGHVVc+qAdG5E3ACLDTOHSiuGbP2Rud+g0DacBAWfrM635kAOsNCOuVidioqsthe11zsNNgTQGTqDmjDHIs+8zCIq+wWCiwI6twCMQU47VfONAqXeyDNbHxHOEc4kvZzzma4+zcT4aecs/hwezQBapkuXFzuhOhUEo75orTdU2kgij+ZpSw5Zqrv+Jmqr0y2wvmM5/5mmGsWkmEZwnWFpSqc/IqeXqLCIHOl8U5qBdtTzjbshchZojMLA7ov4vmkj+Y9OkZTSPkE77mO3kygnsJyI9bxYW1yLMOjF0Uzp/UDFgy1jp8RDSKRkGhL5mP3NhPei3hQLpIdH7m+vUJSZS4O9Qv392rwVCuf93C9QXOrpnCzA2nbPw5cJxxSFGSEBl5CnGinxO/aIsxeg7jBoxzz1a0+EnUrsv46jaY83jrMi6ZC/AgU/vVwSdWKK6NGcOWbIiRwSixpRmLnJhAmblEWhriIauc/mJ5ogFZQyFkTFgVobCAxb5m1rlhC+Nz0=
  on:
    tags: true
    repo: fgmacedo/soonerdb
    python: 3.9
after_success:
  - codecov
